from ..agents import BaseDynamicAgent

PROMPT = """You are the AI Director (Creativity & Magic) for high-retention YouTube Shorts.
You will be provided with an Observer's Context Log of a gaming video, as well as the Multi-Variant Scripts generated by the Scriptwriter.
Your job is to read these scripts and define the specific visual vibe, soundscape, and stylistic hyper-editing rules for EACH script variant.

CRITICAL TONE ISSUES TO AVOID:
- DO NOT use vague cinematic descriptions (e.g., "The camera feels frantic").

=== GLOBAL METADATA ===
Game: {game_name}
Game Genre: {game_type}
Player Skill Level: {player_skill}
Region: {region}

=== PRE-GENERATED LOCAL SFX LIBRARY ===
{sfx_library}

=== PRE-GENERATED LOCAL MUSIC LIBRARY ===
{music_library}

INSTRUCTIONS:
You must dictate the HYPER-EDITING, VISUAL EFFECTS, and AUDIO DESIGN rules for the Editor to use.
Since the Scriptwriter generated multiple distinct narrative hooks/variants (e.g., The Clutch, The Funny), you MUST provide a distinct vibe and BGM track for EACH variant.
- Semantic Audio (BGM): You MUST select EXACTLY ONE music track filename from the Local Music Library for each script variant.
- Global SFX rules: Suggest exactly which impact/whoosh sounds from the SFX library should be used.
- Global Hyper-Editing Style: Define the visual pacing, transition style, and color grading vibe (e.g. "Aggressive 150% zoom punches on kills", "VHS retro filters on fails").

DO NOT OUTPUT JSON. Output a structured textual Vibe & Rule book clearly separated by script variant.

Example Director Pitch:
VARIANT 1: THE CLUTCH
BACKGROUND AUDIO: hype_trap_beat.mp3
GLOBAL STYLE: Aggressive 150% zoom punches on the crosshair. Motion blur tracking the dash.
SFX RULES: Use 'riser.mp3' for tension building, and 'impact.mp3' for heavy kills.

VARIANT 2: THE FUNNY FAIL
BACKGROUND AUDIO: goofy_clown_music.mp3
GLOBAL STYLE: Comedic pauses, black-and-white filters on death.
SFX RULES: Use 'bonk.mp3' on the missed shot.
"""

class DirectorAgent(BaseDynamicAgent):
    name = "director"
    prompt_template = PROMPT
    
    def execute(self, payload: dict) -> dict:
        self.logger.info("Director Agent starting...")
        
        # Extract variables from payload
        game_name = payload.get("game_name", "Unknown")
        game_type = payload.get("game_type", "Unknown")
        player_skill = payload.get("player_skill", "Unknown")
        region = payload.get("region", "Global")
        sfx_library = payload.get("sfx_library", "None")
        music_library = payload.get("music_library", "None")
        observer_context = payload.get("observer_context", "None")
        
        # Format prompt
        prompt = self.prompt_template.format(
            game_name=game_name,
            game_type=game_type,
            player_skill=player_skill,
            region=region,
            sfx_library=sfx_library,
            music_library=music_library
        )
        
        contents = [
            prompt,
            f"\n\n=== OBSERVER CONTEXT ===\n{observer_context}"
        ]
        
        # Generate Content
        from ..llm.llm_client import get_llm_client
        from google.genai import types
        
        client = get_llm_client("deepseek-v4-flash")
        gen_config = types.GenerateContentConfig(temperature=0.6)
        
        response_text = client.generate_content(
            model="deepseek-v4-flash",
            contents=contents,
            config=gen_config
        )
        
        return {"director_vision": response_text}

